server:
 port: 8090
spring:
 application:
  name: accountservice
 datasource:
  url: ${DB_URI:jdbc:mysql://143.198.59.34:3306/accountservice?serverTimezone=UTC}&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  username: ${DB_USERNAME:winny}
  password: ${DB_PASSWORD:Giktek@2022}


